package com.wyz.mapper.estore;

import com.wyz.entity.estore.GoodsClass;
import com.wyz.entity.estore.GoodsClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GoodsClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @SelectProvider(type=GoodsClassSqlProvider.class, method="countByExample")
    int countByExample(GoodsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @DeleteProvider(type=GoodsClassSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @Delete({
        "delete from t_goods_class",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @Insert({
        "insert into t_goods_class (id_parent, class_name, ",
        "describe)",
        "values (#{id_parent,jdbcType=INTEGER}, #{class_name,jdbcType=VARCHAR}, ",
        "#{describe,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(GoodsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @InsertProvider(type=GoodsClassSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(GoodsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @SelectProvider(type=GoodsClassSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="id_parent", property="id_parent", jdbcType=JdbcType.INTEGER),
        @Result(column="class_name", property="class_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="describe", property="describe", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsClass> selectByExample(GoodsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @Select({
        "select",
        "id, id_parent, class_name, describe",
        "from t_goods_class",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="id_parent", property="id_parent", jdbcType=JdbcType.INTEGER),
        @Result(column="class_name", property="class_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="describe", property="describe", jdbcType=JdbcType.VARCHAR)
    })
    GoodsClass selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @UpdateProvider(type=GoodsClassSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsClass record, @Param("example") GoodsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @UpdateProvider(type=GoodsClassSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsClass record, @Param("example") GoodsClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @UpdateProvider(type=GoodsClassSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_class
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    @Update({
        "update t_goods_class",
        "set id_parent = #{id_parent,jdbcType=INTEGER},",
          "class_name = #{class_name,jdbcType=VARCHAR},",
          "describe = #{describe,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GoodsClass record);
}