package com.wyz.entity.estore;

public class GoodsClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_class.id
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_class.id_parent
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private Long id_parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_class.class_name
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private String class_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_class.describe
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_class.id
     *
     * @return the value of t_goods_class.id
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_class.id
     *
     * @param id the value for t_goods_class.id
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_class.id_parent
     *
     * @return the value of t_goods_class.id_parent
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public Long getId_parent() {
        return id_parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_class.id_parent
     *
     * @param id_parent the value for t_goods_class.id_parent
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setId_parent(Long id_parent) {
        this.id_parent = id_parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_class.class_name
     *
     * @return the value of t_goods_class.class_name
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public String getClass_name() {
        return class_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_class.class_name
     *
     * @param class_name the value for t_goods_class.class_name
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setClass_name(String class_name) {
        this.class_name = class_name == null ? null : class_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_class.describe
     *
     * @return the value of t_goods_class.describe
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_class.describe
     *
     * @param describe the value for t_goods_class.describe
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }
}