package com.wyz.entity.estore;

public class Template {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.id
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.C1
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private String c1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.C2
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private String c2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.C3
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private String c3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.C4
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private String c4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.C5
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    private String c5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.id
     *
     * @return the value of t_template.id
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.id
     *
     * @param id the value for t_template.id
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.C1
     *
     * @return the value of t_template.C1
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public String getC1() {
        return c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.C1
     *
     * @param c1 the value for t_template.C1
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setC1(String c1) {
        this.c1 = c1 == null ? null : c1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.C2
     *
     * @return the value of t_template.C2
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public String getC2() {
        return c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.C2
     *
     * @param c2 the value for t_template.C2
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setC2(String c2) {
        this.c2 = c2 == null ? null : c2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.C3
     *
     * @return the value of t_template.C3
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public String getC3() {
        return c3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.C3
     *
     * @param c3 the value for t_template.C3
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setC3(String c3) {
        this.c3 = c3 == null ? null : c3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.C4
     *
     * @return the value of t_template.C4
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public String getC4() {
        return c4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.C4
     *
     * @param c4 the value for t_template.C4
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setC4(String c4) {
        this.c4 = c4 == null ? null : c4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.C5
     *
     * @return the value of t_template.C5
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public String getC5() {
        return c5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.C5
     *
     * @param c5 the value for t_template.C5
     *
     * @mbggenerated Sat Apr 14 10:14:08 CST 2012
     */
    public void setC5(String c5) {
        this.c5 = c5 == null ? null : c5.trim();
    }
}